os: linux
sudo: false
dist: bionic

language: cpp
compiler:
  - gcc
  - clang

install:
  - mkdir -p $HOME/.cache/pkgs
  - if [ "$CXX" = "g++" ]; then
      echo "CXX=g++" > tests/make.inc;
    else 
      echo "CXX=clang++" > tests/make.inc;
    fi

script:
  - cd tests && make

notifications:
  on_success: never
  on_failure: always
